

class GameFunction:
    """Функции игры"""
    def __init__(self):
        ...

    def _check_events(self):
        ...
    def _check_keydown_events(self):
        ...
    def _check_keyup_events(self):
        ...
    def update_game_objects(self):
        ...
